spring:
  application:
    name: Gift And Go Tech Assessment
  datasource:
    url: jdbc:h2:mem:fileprocessor
#    url: jdbc:h2:file:/data/demo
    username: sa
    password: pwd
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true

ipApiBaseUrl: http://ip-api.com